export const BOOK_TRIP_SUCESS='BOOK_TRIP_SUCESS';
export const BOOK_TRIP_FAIL='BOOK_TRIP_FAIL';
export const GET_ALL_RESERVATIONS='GET_ALL_RESERVATIONS';
export const GET_My_RESERVATIONS='GET_My_RESERVATIONS';
export const CONFIRM_RESERVATION='CONFIRM_RESERVATION';
export const CONFIRM_PAYMENT='CONFIRM_PAYMENT';