export const GET_ALL_TRIPS='GET_ALL_TRIPS';
export const GET_ALL_My_TRIPS='GET_ALL_My_TRIPS';
export const LOADING_TRIPS_ERROR='LOADING_TRIPS_ERROR';
export const SHARE_NEW_TRIP='SHARE_NEW_TRIP';
export const SHARE_TRIP_ERROR='SHARE_TRIP_ERROR';